/// A single `term` / `definition` pair.
class DefinitionEntry {
  final String term;
  final String definition;
  DefinitionEntry({required this.term, required this.definition});

  factory DefinitionEntry.fromJson(Map<String, dynamic> json) {
    return DefinitionEntry(
      term: json['term']?.toString() ?? '',
      definition: json['definition']?.toString() ?? '',
    );
  }
}

/// A comparison block. The schema for comparisons is loosely typed
/// (varying keys beyond `feature`), so we keep the raw map and expose
/// `feature` plus the remaining key/value pairs generically.
class ComparisonEntry {
  final String feature;
  final Map<String, String> attributes;

  ComparisonEntry({required this.feature, required this.attributes});

  factory ComparisonEntry.fromJson(Map<String, dynamic> json) {
    final attrs = <String, String>{};
    json.forEach((key, value) {
      if (key != 'feature') attrs[key] = value?.toString() ?? '';
    });
    return ComparisonEntry(
      feature: json['feature']?.toString() ?? '',
      attributes: attrs,
    );
  }
}

class NumberEntry {
  final String value;
  final String unit;
  final String context;

  NumberEntry({required this.value, required this.unit, required this.context});

  factory NumberEntry.fromJson(Map<String, dynamic> json) {
    return NumberEntry(
      value: json['value']?.toString() ?? '',
      unit: json['unit']?.toString() ?? '',
      context: json['context']?.toString() ?? '',
    );
  }
}

class CommandEntry {
  final String command;
  final String purpose;
  CommandEntry({required this.command, required this.purpose});

  factory CommandEntry.fromJson(Map<String, dynamic> json) {
    return CommandEntry(
      command: json['command']?.toString() ?? '',
      purpose: json['purpose']?.toString() ?? '',
    );
  }
}

/// A single learning section within a chapter. Mirrors the knowledge.json
/// section schema field-for-field so the JSON can be regenerated by Gemini
/// without any Dart changes, as long as field names remain the same.
class Section {
  final int sectionId;
  final String title;
  final int startPage;
  final int endPage;

  final List<String> learningObjectives;
  final List<String> keyConcepts;
  final List<DefinitionEntry> definitions;
  final List<String> services;
  final List<String> protocols;
  final List<CommandEntry> commands;
  final List<NumberEntry> numbers;
  final List<ComparisonEntry> comparisons;
  final List<String> advantages;
  final List<String> disadvantages;
  final List<String> prerequisites;
  final List<String> limitations;
  final List<String> bestPractices;
  final List<String> examTraps;
  final List<String> commonConfusions;
  final List<String> realWorldScenarios;
  final List<String> dependencies;

  Section({
    required this.sectionId,
    required this.title,
    required this.startPage,
    required this.endPage,
    required this.learningObjectives,
    required this.keyConcepts,
    required this.definitions,
    required this.services,
    required this.protocols,
    required this.commands,
    required this.numbers,
    required this.comparisons,
    required this.advantages,
    required this.disadvantages,
    required this.prerequisites,
    required this.limitations,
    required this.bestPractices,
    required this.examTraps,
    required this.commonConfusions,
    required this.realWorldScenarios,
    required this.dependencies,
  });

  factory Section.fromJson(Map<String, dynamic> json) {
    List<String> strList(String key) =>
        (json[key] as List? ?? []).map((e) => e.toString()).toList();

    return Section(
      sectionId: (json['section_id'] as num?)?.toInt() ?? 0,
      title: json['title']?.toString() ?? '',
      startPage: (json['start_page'] as num?)?.toInt() ?? 0,
      endPage: (json['end_page'] as num?)?.toInt() ?? 0,
      learningObjectives: strList('learning_objectives'),
      keyConcepts: strList('key_concepts'),
      definitions: (json['definitions'] as List? ?? [])
          .map((e) => DefinitionEntry.fromJson(e as Map<String, dynamic>))
          .toList(),
      services: strList('services'),
      protocols: strList('protocols'),
      commands: (json['commands'] as List? ?? [])
          .map((e) => CommandEntry.fromJson(e as Map<String, dynamic>))
          .toList(),
      numbers: (json['numbers'] as List? ?? [])
          .map((e) => NumberEntry.fromJson(e as Map<String, dynamic>))
          .toList(),
      comparisons: (json['comparisons'] as List? ?? [])
          .map((e) => ComparisonEntry.fromJson(e as Map<String, dynamic>))
          .toList(),
      advantages: strList('advantages'),
      disadvantages: strList('disadvantages'),
      prerequisites: strList('prerequisites'),
      limitations: strList('limitations'),
      bestPractices: strList('best_practices'),
      examTraps: strList('exam_traps'),
      commonConfusions: strList('common_confusions'),
      realWorldScenarios: strList('real_world_scenarios'),
      dependencies: strList('dependencies'),
    );
  }

  /// All searchable free text contained in this section, used by the
  /// global search feature.
  String get searchableText {
    final buffer = StringBuffer()
      ..writeln(title)
      ..writeln(learningObjectives.join(' '))
      ..writeln(keyConcepts.join(' '))
      ..writeln(definitions.map((d) => '${d.term} ${d.definition}').join(' '))
      ..writeln(services.join(' '))
      ..writeln(bestPractices.join(' '))
      ..writeln(examTraps.join(' '))
      ..writeln(commonConfusions.join(' '));
    return buffer.toString().toLowerCase();
  }
}

class Chapter {
  final int chapterId;
  final String title;
  final int startPage;
  final int endPage;
  final int difficulty;
  final int estimatedQuestions;
  final List<Section> sections;

  Chapter({
    required this.chapterId,
    required this.title,
    required this.startPage,
    required this.endPage,
    required this.difficulty,
    required this.estimatedQuestions,
    required this.sections,
  });

  factory Chapter.fromJson(Map<String, dynamic> json) {
    return Chapter(
      chapterId: (json['chapter_id'] as num?)?.toInt() ?? 0,
      title: json['title']?.toString() ?? '',
      startPage: (json['start_page'] as num?)?.toInt() ?? 0,
      endPage: (json['end_page'] as num?)?.toInt() ?? 0,
      difficulty: (json['difficulty'] as num?)?.toInt() ?? 1,
      estimatedQuestions: (json['estimated_questions'] as num?)?.toInt() ?? 0,
      sections: (json['sections'] as List? ?? [])
          .map((e) => Section.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }

  Section? sectionById(int id) {
    for (final s in sections) {
      if (s.sectionId == id) return s;
    }
    return null;
  }
}
